### ISSUE TITLE
Callback implementation

### ISSUE THREAD

**Issue by Todd442** [sunkin351/FmodAudio#12]
Not finding the abstractions for channel callbacks. 

In the native C# Language, you would implement the call back function this way:
 // Define the channel callback function
        private static RESULT ChannelCallback(IntPtr channelControlRaw,
                                              CHANNELCONTROL_TYPE controlType,
                                              CHANNELCONTROL_CALLBACK_TYPE callbackType,
                                              IntPtr commandData1,
                                              IntPtr commandData2)
        {
            if (controlType == CHANNELCONTROL_TYPE.CHANNEL &&
                callbackType == CHANNELCONTROL_CALLBACK_TYPE.END)
            {
                // The sound has reached its end point

                // Write your notification logic here
                Console.WriteLine("The sound has completed playing.");

                return RESULT.OK;
            }

            return RESULT.OK;
        }

Looking through your lib, I'm not finding the corollary types. Of course, you could have implemented this in a different manner like Events but don't see that either.

**Comment by sunkin351** [comment]
Is [this](https://github.com/sunkin351/FmodAudio/blob/master/FmodAudio/Channel.cs#L299) not the function you're looking for?

**Comment by Todd442** [comment]
Yea saw that but when you need to implement the actual method you need the appropriate object types:

**CHANNELCONTROL_TYPE** controlType,
**CHANNELCONTROL_CALLBACK_TYPE** callbackType,

Those are what I couldn't find in the repository. Of course, it's not beyond me to miss something.

**Comment by sunkin351** [comment]
They are actually referenced in the function pointer parameter definition.
```cs
public override unsafe void SetCallback(delegate* unmanaged<IntPtr, ChannelControlType, ChannelControlCallbackType, void*, void*, void> callback)
```

And both are literally the first 2 type definitions in [Enums.cs](https://github.com/sunkin351/FmodAudio/blob/master/FmodAudio/Enums.cs). I actually don't understand what's wrong...

**Comment by sunkin351** [comment]
It would seem that part of your disconnect is that you assumed I would keep with the naming conventions of the "official" C# bindings for Fmod, provided by the Fmod Team. I do not.

Part of the reason I was moved to create this 3rd party binding in the first place was to create a more intuitive and "C#" development experience. All Type and Member definitions (with the exception of some `enum` members) are pascal case without underscores.

**Comment by sunkin351** [comment]
Closed as there is no issue.
