### ISSUE TITLE
Loading Fmod Studio Bank files?

### ISSUE THREAD

**Issue by Todd442** [sunkin351/FmodAudio#13]
Not finding a way in the lib to load Fmod bank files. 

In my case, l'd like to use the Bank file with a "Programmer Instrument" so I can load the audio stream on demand during program execution and apply the appropriate audio effects. 

Background:
In my case, I'm apply audio effects to dynamically generated speech. I can certainly craft the effects via code but was hoping to take advantage to a Bank file that can be updated outside the code.

**Comment by sunkin351** [comment]
Ok, so, unless the Core API supports loading Fmod Studio Bank files, that's outside the scope of this library. If there's ever enough support, I'll wrap the Studio API as well, but for right now that's not supported on my end.

**Comment by Todd442** [comment]
OK groovy
Thanks for the response I'll approach it differently

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Todd442** [comment]
Thanks again for the response
