### ISSUE TITLE
Illegal to use on iOS platforms

### ISSUE THREAD

**Issue by Perksey** [sunkin351/FmodAudio#3]
Just thought I'd let you know that the ADL license doesn't allow static linking, which means that iOS can't be supported without breaching the license. If this is an issue, please contact Firwood Softwar eto discuss purchasing a commercial license/open-source grant similar to those given to OpenTK and Silk.NET.

**Comment by sunkin351** [comment]
I can't say I intended this for use on IOS... If IOS won't allow dynamic linking, they are out of the picture in my book anyway. (I'm not paying money to write code. Sorry)

**Comment by sunkin351** [comment]
And one other comment, if anyone does decide to use this for IOS development, Its none of my business, as I'm using MIT licensing. (Do forgive me if I'm not understanding the implications of this)

**Comment by sunkin351** [comment]
One more comment about this... My .NET 5 release will remove any and all dependence on ADL, in favor of a custom source generator.
