### ISSUE TITLE
How to use and configure DSP of type FFT?

### ISSUE THREAD

**Issue by madsami** [sunkin351/FmodAudio#4]
Couldn't find any examples that showed how to do this in the Examples or general source.
I need to access the spectral data e.g. fftDsp.GetParameterData(..) -> to find ParameterFFT.Spectrum, but the examples from the official FMOD source does not match the syntax of the FmodAudio implementation, so I wanted to ask directly.
Any help would be appreciated, thanks.

**Comment by sunkin351** [comment]
The API surface area is more or less 1-1 with the C API, with some C# syntax sugar mixed in. I don't remember there being an example for this in the Fmod implementation download, if you can point me to where its at I can whip up an example of how to do it.

**Comment by madsami** [comment]
Thanks for the prompt reply.
I've been looking at pages like these:
DSP FFT: https://documentation.help/FMOD-Studio-API/FMOD_DSP_FFT.html
FFT WINDOW TYPES: https://documentation.help/FMOD-Ex/FMOD_DSP_FFT_WINDOW.html
And threads like these that show namespaces and defined parameter names e.g. _fft.getParameterData((int)FMOD.DSP_FFT.SPECTRUMDATA, ... )_
https://qa.fmod.com/t/getting-spectrum-of-master-channel-in-unity/12579

In the end I was **not** able to get spectral data in my code, but I don't know if this method is correct. I'll paste it below:
```
Setup:
{
..
fftPass = System.CreateDSPByType(DSPType.FFT);
fftPass.SetParameterInt(0, 2); // Length ?
fftPass.SetParameterInt(1, WindowSize * 2); // ChannelCount ?
fftPass.Active = true;
fftPass.Bypass = true;

var master = System.MasterChannelGroup;
master.AddDSP(0, fftPass);
..
}

During recording/playback:
{
...
System.Update(); and so on
...
FFT relevant:
 var ptr = fftPass.GetParameterData(2, out var len);
var data = new ReadOnlySpan<ParameterFFT>(ptr, (int)len);
// ParameterFFT fftdata = (ParameterFFT) Marshal.PtrToStructure(ptr, typeof(ParameterFFT));
var spectrum = data[0].Spectrum;
...
}
```

Please advise

Edit: Spoke too soon. I'm able to get **_a_** FFT spectral object without crashing, but it doesn't seem to hold any data in its spectrum[32] lol

**Comment by madsami** [comment]
> 
> 
> The API surface area is more or less 1-1 with the C API, with some C# syntax sugar mixed in. I don't remember there being an example for this in the Fmod implementation download, if you can point me to where its at I can whip up an example of how to do it.

Found the actual official description on how to do it here https://fmod.com/resources/documentation-unity?version=2.2&page=examples-spectrum-analysis.html
Would be nice if I could access the parameter namespace for using FMOD.DSP_FFT.SPECTRUMDATA, FMOD.DSP_FFT.WINDOWTYPE, FMOD.DSP_FFT_WINDOW.HANNING and so on.
If these already are available in FmodAudio somehow, I wasn't able to find them.

**Comment by sunkin351** [comment]
Lesson 1 in modern marshalling. `Marshal.PtrToStructure()` is useless, . ^_^ It will only provide a copy of the data in what's likely a non-thread-safe manner. The pointer is to the DSP's personal copy to the data and is updated as it runs.

It looks like I'll be porting `fmod_dsp_effects.h` to FmodAudio here in a bit.

**Comment by madsami** [comment]
Thanks for looking into it. It would surely make it easier to access spectral data :) Really happy for FmodAudio and that it's being actively supported.

**Comment by sunkin351** [comment]
Is there a reason you're avoiding casting that pointer to `ParameterFFT*`? Cause you can totally do that.

Edit:
The definition is as follows
```cs
    public unsafe struct ParameterFFT
    {
        static ParameterFFT()
        {
            if (sizeof(SpectrumArray) != IntPtr.Size * 32)
            {
                throw new Exception("The size of ParameterFFT.SpectrumArray is not the size of 32 pointers.");
            }
        }

        public int Length;
        public int ChannelCount;
        private SpectrumArray _spectrum;

        public Span<IntPtr> Spectrum => MemoryMarshal.CreateSpan(ref _spectrum.FirstElement, 32);

        private struct SpectrumArray
        {
            public IntPtr FirstElement;
            public IntPtr Element01;
            public IntPtr Element02;
            public IntPtr Element03;
            public IntPtr Element04;
            public IntPtr Element05;
            public IntPtr Element06;
            public IntPtr Element07;
            public IntPtr Element08;
            public IntPtr Element09;
            public IntPtr Element10;
            public IntPtr Element11;
            public IntPtr Element12;
            public IntPtr Element13;
            public IntPtr Element14;
            public IntPtr Element15;
            public IntPtr Element16;
            public IntPtr Element17;
            public IntPtr Element18;
            public IntPtr Element19;
            public IntPtr Element20;
            public IntPtr Element21;
            public IntPtr Element22;
            public IntPtr Element23;
            public IntPtr Element24;
            public IntPtr Element25;
            public IntPtr Element26;
            public IntPtr Element27;
            public IntPtr Element28;
            public IntPtr Element29;
            public IntPtr Element30;
            public IntPtr Element31;
        }
    }
```
Treat `ParameterFFT.Spectrum` as an array of `float*` (float pointers), each with a length of `ParameterFFT.Length`
(Assuming I'm understanding the original C definition correctly.)

Edit2:
Adding helper methods like they do in the original wrapper for this.

**Comment by sunkin351** [comment]
Ported the rest of those enumerations to C#. And I also added a few helper methods to `ParameterFFT` to assist you.

**Comment by sunkin351** [comment]
Uploaded new Nuget Version with the additions/changes and version bump. Are these adequate?

**Comment by madsami** [comment]
Thank you very much for implementing the changes! I'm now able to retrieve spectral information without any apparent issues. :)
