### ISSUE TITLE
Use with FMOD version 2.02

### ISSUE THREAD

**Issue by hubbux** [sunkin351/FmodAudio#5]
Hi, I wanted to ask if there are big changes necessary to get it to work with 2.02.
Right now it throws a version mismatch with the DLLs. If its possible to remove the version check, do you know if it will run with 2.02?
Btw I need 2.02 since I am working on armv8 and 2.01 only supports up to armv6 as far as I know.

I also know about the default included wrapper but I would really like to use yours.

**Comment by sunkin351** [comment]
I'll take a look, and I'll probably modify the version check so that it simply verifies the major version of Fmod.

**Comment by sunkin351** [comment]
The temporary workaround would be to create your system object directly from the object you get from `Fmod.Library`

**Comment by sunkin351** [comment]
Wait, why is it throwing? What error are you getting exactly? It should only throw if the Fmod version is lower than 2.01...
Edit: Stack Trace please. ^_^

**Comment by sunkin351** [comment]
Releases for Fmod 2.2.0 and 2.2.1 have been published.
