### ISSUE TITLE
Should this work an android?

### ISSUE THREAD

**Issue by ChriD** [sunkin351/FmodAudio#8]
Hi, I try to use this lib with .NET6 MAUI
It works fine in windows, but on android it says
`System.PlatformNotSupportedException: 'Operation is not supported on this platform.'`
Could this be because it can't find the fmod libs for android?

**Comment by sunkin351** [comment]
Stack trace and operation details please. ^_^

**Comment by ChriD** [comment]
I use Visual Studio 2022 17.2.0 Preview 1

![image](https://user-images.githubusercontent.com/2505067/154325306-9748c087-51e1-4572-a9e6-bd59e0ed5ac1.png)

The error raises from here
![image](https://user-images.githubusercontent.com/2505067/154325454-d45ec5c3-fabc-47d7-b610-2cf7d943a6c7.png)

I think there is the "isAndroid" condition missing...
https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem.isandroid?view=net-6.0

So this indicates that the lib is not ready for and was never tried for android?
But it may work out of the box if the android condition is beeing added...

**Comment by sunkin351** [comment]
What's the lib name on android?

**Comment by ChriD** [comment]
Sorry, i am away from my computer, right now typing from phone, i can tell you tomorrow.

**Comment by sunkin351** [comment]
Found the docs outlining it. I'll update the code and push a nuget update as soon as I can.

**Comment by sunkin351** [comment]
Fixed with commit c807436cab7b96c2d8847aeae60470d6edb6ccf6
Nuget package update soon to follow.
