### ISSUE TITLE
Example Project unable to find Native Fmod DLL

### ISSUE THREAD

**Issue by zydjohnHotmail** [sunkin351/FmodAudio#9]
Hello:
I want to try to run the example project in this repo.
I downloaded the repo souce code, unzip it, and open it with Visual Studio 2022.
I set up Example project as the "Set as Startup project", I can see  the console window displayed.
But when I press return key, I got the following error:
System.DllNotFoundException: Unable to load DLL 'fmod.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at FmodAudio.Fmod.<>c.<.cctor>b__35_0() in D:\GitHubRepos\FmodAudio-master\FmodAudio\Fmod.cs:line 114
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at FmodAudio.Fmod.get_Library() in D:\GitHubRepos\FmodAudio-master\FmodAudio\Fmod.cs:line 117
   at FmodAudio.Fmod.CreateSystem() in D:\GitHubRepos\FmodAudio-master\FmodAudio\Fmod.cs:line 200
   at Examples.Base.Example.Initialize() in D:\GitHubRepos\FmodAudio-master\Examples\Base\LibraryExample.cs:line 32
   at Examples._3DExample.Initialize() in D:\GitHubRepos\FmodAudio-master\Examples\_3D_Example.cs:line 41
   at Examples.Program.StartExample(Type exampleType) in D:\GitHubRepos\FmodAudio-master\Examples\Program.cs:line 158

D:\GitHubRepos\FmodAudio-master\Examples\bin\Debug\net5.0\Examples.exe (process 36340) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

Let me know how I can fix this issue.
By the way, I am using Windows 10 (Version 21H2).
Besides, can I use the repo to merge/concat mutliple audio files (aac format)?
Thanks,

**Comment by sunkin351** [comment]
Good day friend. The exception is because I do not distribute the native library with the package. Please refer to the ReadMe.md in the root directory of this repository for a link to the download.

**Comment by sunkin351** [comment]
> Besides, can I use the repo to merge/concat mutliple audio files (aac format)?

There is a way to Play each sound such that its as if they were one sound. Takes a little bit of math and use of the API. Otherwise, no concat is available.

**Comment by zydjohnHotmail** [comment]
Hello:
I register an account and downloaded the following packages for Windows:
FMOD Studio 2.02.06 and FMOD Engine 2.02.06
But after the installation, I still got the same error when running the example project.
Please advise!
By the way, what kind of math I have to do to use API in order to merge/concat multiple audio files?

**Comment by sunkin351** [comment]
You need to place a copy of fmod.dll in your application's directory/folder. That's the first place it looks for it.

Or you can point FmodAudio at it with `Fmod.SetLibraryLocation()`

**Comment by sunkin351** [comment]
> By the way, what kind of math I have to do to use API in order to merge/concat multiple audio files?

`GaplessPlaybackExample.cs` holds the answer to that.

**Comment by zydjohnHotmail** [comment]
Hello:
I copied one fomd.dll from here:
C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\examples\bin
To the FMOD/Example project in here:
D:\GitHubRepos\FmodAudio-master\Examples\bin\Debug\net5.0
But I still got the same error as before.
Please advise if I copied the wrong dll, or other issues.
I found at least 4 fomd.dll files:
C:\>dir fmod.dll /s
 Volume in drive C has no label.
 Volume Serial Number is 8C0B-783A

 Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\examples\bin

03/15/2022  06:25 AM         1,552,384 fmod.dll
               1 File(s)      1,552,384 bytes

 Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\lib\x64

03/15/2022  06:25 AM         1,843,200 fmod.dll
               1 File(s)      1,843,200 bytes

 Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\lib\x86

03/15/2022  06:25 AM         1,552,384 fmod.dll
               1 File(s)      1,552,384 bytes

 Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\studio\examples\bin

03/15/2022  06:25 AM         1,552,384 fmod.dll
               1 File(s)      1,552,384 bytes

**Comment by sunkin351** [comment]
I take it this is your first time doing anything with native interop. There's multiple versions depending on target OS and Architecture. If you are using 64-bit windows, you use the x64 variant, if you're using 32-bit, the x86 variant.

**Comment by zydjohnHotmail** [comment]
Hello:
I figured out the loading DLL issue:
In example project, have to add argv[1] to fmod.dll path:
Like this:
D:\GitHubRepos\FmodAudio-master\Examples\bin\x64\Debug\net5.0
Change the project to use X64 CPU, copy the original x64 fmod.dll to the path.
C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\lib\x64\fmod.dll
The misleading part is the x64 fmod.dll is located inside:
C:\Program Files (x86)\FMOD SoundSystem\ folder.
However, when I run the project again, I got the following errors:
System.ArgumentException: An invalid parameter was passed to this function.
   at FmodAudio.FmodHelpers.CheckResult(Result result) in D:\GitHubRepos\FmodAudio-master\FmodAudio\FmodHelpers.cs:line 119
   at FmodAudio.Sound.Set3DMinMaxDistance(Single min, Single max) in D:\GitHubRepos\FmodAudio-master\FmodAudio\Sound.cs:line 101
   at Examples._3DExample.Initialize() in D:\GitHubRepos\FmodAudio-master\Examples\_3D_Example.cs:line 54
   at Examples.Program.StartExample(Type exampleType) in D:\GitHubRepos\FmodAudio-master\Examples\Program.cs:line 158

D:\GitHubRepos\FmodAudio-master\Examples\bin\x64\Debug\net5.0\Examples.exe (process 20620) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

Please advise on how to fix this issue.
By the way, I can't change the selection, I can't move cursor to other selections, so I can only select the first one: [-]: 3D Example
Whick keyboard or cursor I can use to choose other selections?
Thanks,

**Comment by sunkin351** [comment]
Uhh... I don't wrap the Studio API, only the Core API. Someone expressed interest in creating a pull request with support for the studio API, but that was just this morning. It'll probably be a while.

Edit: this is judging based off the path you chose for your fmod.dll

**Comment by zydjohnHotmail** [comment]
Hello:
I don't know the difference between Studio API and Core API.
I installed 2 package: FMOD Studio 2.02.06 and FMOD Engine 2.02.06
And I found only 4 files with the name: fmod.dll.
If I want to target X64 CPU, then let me know which one I should use?
C:>dir fmod.dll /s
Volume in drive C has no label.
Volume Serial Number is 8C0B-783A

Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\examples\bin

03/15/2022 06:25 AM 1,552,384 fmod.dll
1 File(s) 1,552,384 bytes

Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\lib\x64

03/15/2022 06:25 AM 1,843,200 fmod.dll
1 File(s) 1,843,200 bytes

Directory of C:\Program Files (x86)\FMOD SoundSystem\FMOD Studio API Windows\api\core\lib\x86

**Comment by sunkin351** [comment]
You downloaded the Studio API, not the Core API. If you want to use FmodAudio, please go back and download the Core API.

**Comment by zydjohnHotmail** [comment]
Hello:
Please look at the installation screen shot. I already installed it once, before I will do it twice.
I don't think I can install so-called "Core API".
![FMODStudioAPINOK](https://user-images.githubusercontent.com/45263518/166328693-3884be00-e3ef-4925-8d87-d956e8b1dba9.png)

**Comment by sunkin351** [comment]
Forgive my confusion, its included in the install, at least according to the website. File path to the appropriate binaries should be `<Your Fmod Dir>/api/core/lib/<your architecture>/fmod.dll`. Let it be known I have not tested anything with 32-bit, so no guarantees that scenario will work.

**Comment by zydjohnHotmail** [comment]
Hello:
This is my logic: I installed the package, if fmod.dll is included, then using DOS command: dir fmod.dll /s will find the file.
I saw 4 files names are fmod.dll, then if none of them is the CORE API, then what you think?
Let me suggest that if you have a Windows 10 PC, (I hope it is not very tough to get one), then you try to install the packages, and try to use CORE API, to see if it works.
If you see the same screen shot as I showed here, then you may not be able to use the core API.
Please do some testing, and let me know the result.
Thanks,

**Comment by sunkin351** [comment]
I've installed this SDK multiple times over the development of FmodAudio. It's there, and I gave you the path to find it. Furthermore, you can specify its location to the example project by giving it as the first command line argument.

Beyond this, I do not know how to help you.

**Comment by zydjohnHotmail** [comment]
Hello:
From my experience, if you can find a new PC, which has NOT installed any SDK or other FmodAudio, then try again.  Because, if you use a PC which has been installed SDK multiple times, the issue is not there.
But installation from a new PC, you may find some issue.

**Comment by sunkin351** [comment]
What are you trying to tell me? My library does not look for the native binary anywhere special (e.g. it lets the OS look for it instead) unless you give it a path to look (via `Fmod.SetLibraryLocation()`), and it certainly doesn't rely on the SDK being installed.

And if you're wondering why I don't ship the native binaries with the package, I was told [by the Fmod team themselves](https://qa.fmod.com/t/distributing-fmod-with-a-wrapper-library/16776) that they didn't want me shipping them with FmodAudio. So that much is out of the question.
